init 5 python:
    addEvent(
        Event(
            persistent._mas_mood_database,
            eventlabel="mas_mood_insecure",
            prompt="...不安全.",
            category=[store.mas_moods.TYPE_BAD],
            unlocked=True
        ),
        code="MOO"
    )
    addEvent(
        Event(
            persistent._mas_mood_database,
            eventlabel="mas_mood_loved",
            prompt="...被爱着.",
            category=[store.mas_moods.TYPE_GOOD],
            unlocked=True
        ),
        code="MOO"
    )
    addEvent(
        Event(
            persistent._mas_mood_database,
            eventlabel="mas_mood_guilty",
            prompt="...内疚.",
            category=[store.mas_moods.TYPE_BAD],
            unlocked=True
        ),
        code="MOO"
    )